### ISSUE TITLE
createContact is returning null result

### ISSUE THREAD

**Issue by trueninjaturtle** [sendinblue/APIv3-nodejs-library#113]
Doing something like the below returns me an empty object. Upgraded to the latest version but no succes. Some subscriptions already exist, some not, but calls return data as null.

```
let CreateContact = {
      email: item.Email_address,
      listIds: [5],
      emailBlacklisted: false,
      smsBlacklisted: false,
      updateEnabled: true
  };
ContactsApi.createContact(CreateContact).then(function(data) {
    console.log('API called successfully. Returned data: ' + JSON.stringify(data));
}, function(error) {
    console.error(error);
});
```

**Comment by shubhamUpadhyayInBlue** [comment]
Hi @trueninjaturtle 

The possibility is that the email that you are passing already exists and since you are passing updateEnabled: true it will return 204 status code without anything in the response body. 

I am assuming this scenario. Rest if you can provide me with some more details like the exact payload so that I can replicate and help you better.
Thanks!

**Comment by shubhamUpadhyayInBlue** [comment]
Closing this issue since there is no reply for a long time. If you are still facing any issues you can open another one. Thanks!
