### ISSUE TITLE
Update boolean attribute

### ISSUE THREAD

**Issue by germainvictor** [sendinblue/APIv3-nodejs-library#114]
Hello,
I am trying to update a list of attributes from your sdk with this [endpoint](https://developers.sendinblue.com/reference/importcontacts-1).

However, it is impossible to set or update an attribute that is of type boolean.
I tried with the value true/false and 0/1 but it does not work .

Do you have any solutions?

**Comment by shubhamUpadhyayInBlue** [comment]
Hi @germainvictor 
Can you please share some sample data from the `fileUrl` or the `fileBody` that you are passing **while using** the **contact import endpoint**? 

I would like to see the structure of the data that you are trying to import.

FYI in boolean type of attributes, we expect either `true` or `false`.

Also, I assume that you have created an attribute with ```"category": "normal" and "type": "boolean"```

Happy to help!

**Comment by germainvictor** [comment]
Hi, 

Here is an example of a `fileBody` : 
````
EMAIL;PRENOM;NOM;AUTO_IS_SSO;AUTO_SSO_DOMAIN_NAME;AUTO_USER_ONBOARDED_TOTAL;AUTO_ORGANIZATION_NAME;AUTO_PROJECT_IN_PROGRESS_ORGANIZATION_TOTAL;AUTO_MONTHLY_BUDGET;AUTO_LAST_PROJECT_ORGANIZATION_NAME;AUTO_LAST_PROJECT_ORGANIZATION_DESCRIPTION
random1@random.com;Project creator;org 1;false;;9;Matters;9;100;CFP 4 Project 2;Energy for all 2!
random2@random.tech;Project backer;org 1;false;;9;Matters;9;100;CFP 4 Project 2;Energy for all 2!
````

> Also, I assume that you have created an attribute with` "category": "normal" and "type": "boolean"`

I confirm that the attribute is: `"category": "normal" and "type": "boolean"`

I contacted customer service and they told me that (but it doesn't work): 
> I would like to inform you that in order to update Boolean attributes, you have to use the true or false value and also add the attribute within "..".


Thank you for your help!

**Comment by shubhamUpadhyayInBlue** [comment]
Hi @germainvictor 
I checked and found that there is an inconsistency on our side with the usage of boolean attributes. The solution that I suggested above works fine for the single create contact endpoint. But,

- When you use the contact import API you have to pass the values of boolean attributes as `yes` or `no`
Example: ```EMAIL;BOOL\n"random1@random.com";yes\n"random2@random.tech";no```

So, instead of passing `true` you will have to pass `yes` and for `false` you must pass `no`. It is a known issue and we would fix it on our side. Apologies for the inconvenience caused.

Do let me know in case you have any queries further.
Happy to help!

**Comment by germainvictor** [comment]
It works very well 🔥

Thank you for your reply !
