### ISSUE TITLE
smtpBlacklistSender not working well

### ISSUE THREAD

**Issue by regevbr** [sendinblue/APIv3-nodejs-library#46]
Trying to set smtpBlacklistSender = [] or [''] on a contact doesnt re enable a blacklisted user
Also there is no way to see if that property is set via the web ui, nor the api response of getContactInfo...

**Comment by shubhamUpadhyayInBlue** [comment]
Hi @regevbr 
I know it might be irrelevant now since it is a late reply. Apologies for that. But, to blacklist or un-blacklist the user you need to pass the `emailBlacklisted` as true or false in the payload during contact create/update.
[API reference](https://developers.sendinblue.com/reference/createcontact)
